In [3]:
import numpy as np
from numpy import array
import math

$$
\text{nopeus}=\sqrt{\frac{\text{kantama}\cdot 9.82\ \text{m}/\text{s}^2}{\sin{\left( 2\cdot \text{kulma} \right)}}}.
$$

In [13]:
def nopeus(kulma, kantama):
    import numpy as np
    # Kirjoita vastauksesi tämän funktiorakenteen sisälle:
    
    # muutetaan parametrit oikeaan muotoon
    kulma_arr = np.array(kulma)
    kantama_arr_cm = np.array(kantama)
    
    # muutetaan kantama (cm) metreiksi (m)
    kantama_arr_m = kantama_arr_cm / 100
    
    # muutetaan kulma (asteet) radiaaneksi
    
    kulma_arr_rad = np.radians(kulma_arr)
    
    # laskukaava
    
    m = kantama_arr_m * 9.82
    k = np.sin(2*kulma_arr_rad)
    mk = np.sqrt(m/k)
    
    
    return mk
    # Älä kirjoita missään tapauksessa muita print komentoja tämän rakenteen sisälle, koska silloin vastauksesi tulkitaan virheelliseksi.
    
    # Lopuksi tulostetaan määrittämäsi numpy taulukko nopeus:
print(nopeus([10, 15, 20, 25, 30], [22.7, 21.9, 26.1, 28.8, 29.8]))
print(nopeus([35, 40, 45, 50, 55], [27.7, 30.6, 32.3, 32.3, 30.4]))

[2.55295306 2.07392382 1.99683532 1.92143193 1.83822454]
[1.70138547 1.74679012 1.78097164 1.79465625 1.78237724]


In [57]:
# Voit testata funktiotasi seuraavalla lähtödatalla:
kulma = [10, 15, 20, 25, 30]
kantama = [22.7, 21.9, 26.1, 28.8, 29.8]

def nopeus(kulma, kantama):
    
    # muutetaan parametrit oikeaan muotoon
    kulma_arr = np.array(kulma)
    kantama_arr_cm = np.array(kantama)
    
    # muutetaan kantama (cm) metreiksi (m)
    kantama_arr_m = kantama_arr_cm / 100
    
    # muutetaan kulma (asteet) radiaaneksi
    
    kulma_arr_rad = np.radians(kulma_arr)
    
    # laskukaava
    
    m = kantama_arr_m * 9.82
    k = np.sin(2*kulma_arr_rad)
    mk = np.sqrt(m/k)
    
    
    return mk


print(nopeus(kulma, kantama))

[2.55295306 2.07392382 1.99683532 1.92143193 1.83822454]


In [52]:
'''[2.55295306 2.07392382 1.99683532 1.92143193 1.83822454]'''

'[2.55295306 2.07392382 1.99683532 1.92143193 1.83822454]'

## 2. Looginen valinta ja laskenta NumPy taulukoilla

Tee NumPy taulukoita hyväksikäyttäen funktio **vertaa(luvut1, luvut2)**, joka ottaa argumenteikseen python taulukot (luvut1 ja luvut2) ja tekee seuraavat laskutoimitukset:
* Luodaan taulukoista "luvut1" ja "luvut2" uudet saman kokoiset NumPy taulukot, joissa on samat lukuarvot.
* Jatkolaskut tehdään pelkästään luotujen NumPy taulukoiden avulla.
* Jos taulukossa "luvut1" alkio rivillä i ja sarakkeessa j on pienempi kuin taulukossa "luvut2" alkio rivillä i ja sarakkeessa j, tulostetaan taulukkoon "luvut1" riville i ja sarakkeeseen j kokonaisluku "-1".
* Lasketaan "tulos" taulukoksi alkioittainen summa "luvut1" ja "luvut2" taulukoiden arvoista.
* Alkioittaisessa summassa lasketaan yhteen summattavien taulukoiden alkiot, joilla on sama rivi- ja sarakeindeksi.
* Annetaan vastaukseksi "tulos" taulukko tulosteena.

Funktiolle **vertaa** annettavat (3 x 3) python taulukot ovat:
* luvut1 = [[12, 2, 4], [5, 1, 2], [9, 3, 45]]
* luvut2 = [[11, 9, 32], [2, 3, 1], [0, 3, 10]]

**Esimerkiksi** vertaa(luvut1, luvut2) tulostaa:
<img src="https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta1/.s20harkkatd/teht2.png" width="110"/>

**Huom!** Tässä tehtävässä ei saa käyttää for silmukoita. Tutustu NumPy [taulukon suodatukseen Boolean taulukon avulla](https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta1/s20kerta1.html#7).



In [30]:
luvut1 = [[12, 2, 4], [5, 1, 2], [9, 3, 45]]
luvut2 = [[11, 9, 32], [2, 3, 1], [0, 3, 10]]


def vertaa(luvut1, luvut2):
    
    
    # Luodaan taulukoista "luvut1" ja "luvut2" uudet saman kokoiset NumPy taulukot, joissa on samat lukuarvot.
    
    arr1 = np.array(luvut1)
    arr2 = np.array(luvut2)
   
    
    
    '''Jos taulukossa "luvut1" alkio rivillä i ja sarakkeessa j on pienempi kuin taulukossa "luvut2" alkio rivillä i ja sarakkeessa j, 
      tulostetaan taulukkoon "luvut1" riville i ja sarakkeeseen j kokonaisluku "-1".'''
    
    arr1[arr1 < arr2] = -1
    
    
    
    
    # Lasketaan "tulos" taulukoksi alkioittainen summa "luvut1" ja "luvut2" taulukoiden arvoista.
    tulos = arr1 + arr2
     


vertaa(luvut1, luvut2)

array([[23,  8, 31],
       [ 7,  2,  3],
       [ 9,  6, 55]])

In [29]:
kulma = [10, 15, 20, 25, 30]
kantama = [22.7, 21.9, 26.1, 28.8, 29.8]

arr1 = np.array(luvut1)
arr2 = np.array(luvut2)

arr1[arr1 < arr2] = -1

print(arr1)

[[12 -1 -1]
 [ 5 -1  2]
 [ 9  3 45]]
