# Koneoppiminen: Osa 3: Naiivi Bayes-luokittelija

In [3]:
# Kirjoita tähän tietosi!
student_name = 'Ville Karjalainen'
student_id = 'AA5075'

## Tehtävä 1
### Aihe: Artificial Characters Data Set

4 pistettä

1. Tutustu *Wine Data Set* -aineistoon osoitteessa https://archive.ics.uci.edu/ml/datasets/Wine .

2. Lataa aineisto ja aseta sarakkeiden nimet. 

3. Jaa aineisto koulutus- ja testausaineistoon käyttäen `scikit-learn`-kirjaston [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)-funktiota.  

4. Normalisoi sarakkeet välille 0...1 `scikit-learn`-kirjaston `preprocessing`-moduulin [minmax_scale](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.minmax_scale.html#sklearn.preprocessing.minmax_scale)-funktiolla.

- Tallenna koulutusaineisto ja sen luokkamuuttuja muuttujiin `X_train`, `y_train`,
- ja toisaalta testausaineiston `X_test`, `y_test`. 

Aseta testausjoukon kooksi 33% ja satunnaisuuden siemeneksi `1900`.

Vinkki: älä skaalaa luokkamuuttujaa. 

Vinkki: muista että luokkamuuttuja ei mene `X`-muuttujiin.

In [4]:
# Kirjoita toteutuksesi tähän soluun. 
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression



# aseta sarakkeiden nimet ja määritä datan url
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'

columns = [
'Class',
'Alcohol',
'Malic acid',
'Ash',
'Alcalinity of ash',
'Magnesium',
'Total phenols',
'Flavanoids',
'Nonflavanoid phenols',
'Proanthocyanins',
'Color intensity',
'Hue',
'OD280/OD315 of diluted wines',
'Proline'
]

# Lataa aineisto muuttujaan 
data = pd.read_csv(url, names=columns)


# Jaa aineisto koulutus- ja testausaineistoon käyttäen scikit-learn-kirjaston train_test_split-funktiota.
X = data.drop('Class', 1)
y = data['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    # Aseta testausjoukon kooksi 33% ja satunnaisuuden siemeneksi 1900
                                                    test_size= 0.33, random_state= 1900)



# Normalisoi sarakkeet välille 0...1 scikit-learn-kirjaston preprocessing-moduulin minmax_scale-funktiolla.
scaler = MinMaxScaler()
X_train = pd.DataFrame(scaler.fit_transform(X_train), columns = X_train.columns)
X_test = pd.DataFrame(scaler.transform(X_test), columns = X_test.columns)

In [5]:
# Tehtävän vastaukset. Huom! Älä muokkaa tätä solua, vaan aja se, kun olet suorittanut tehtävän. 
# Tallenna vastauksesi X_train- X_test-muuttujiin.
print(f'X_train columns: {X_train.columns}')
print(f'X_train: {X_train}')
print(f'X_test: {X_test}')

X_train columns: Index(['Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium',
       'Total phenols', 'Flavanoids', 'Nonflavanoid phenols',
       'Proanthocyanins', 'Color intensity', 'Hue',
       'OD280/OD315 of diluted wines', 'Proline'],
      dtype='object')
X_train:       Alcohol  Malic acid       Ash  Alcalinity of ash  Magnesium  \
0    0.288690    0.531621  0.196078           0.414894   0.246377   
1    0.848214    0.849802  0.346405           0.468085   0.144928   
2    0.550595    0.444664  0.457516           0.468085   0.492754   
3    0.157738    0.258893  1.000000           0.920213   0.710145   
4    0.636905    0.365613  0.437908           0.468085   0.724638   
..        ...         ...       ...                ...        ...   
114  0.547619    0.764822  0.509804           0.547872   0.231884   
115  0.854167    0.185771  0.274510           0.255319   0.449275   
116  0.479167    0.122530  0.209150           0.297872   0.434783   
117  0.250000    0.70553

## Tehtävä 2
### Aihe: Gaussian Naive Bayes

2 pistettä

Käytä `scikit-learn`-kirjastosta löytyvää *Gaussian Naive Bayes* -menetelmää aineiston luokittelemiseksi.

Ennnusta testiaineiston luokka. Tallenna ennusteet `y_pred`-muuttujaan.

In [17]:
# Kirjoita toteutuksesi tähän soluun.

# tuodaan tarvittavat kirjastot
from sklearn.naive_bayes import GaussianNB


# tehdään malli
model = GaussianNB()


# koulutetaan malli
model.fit(X_train, y_train)


# tallennetaan y_pred -nimiseen muuttujaan koneoppimisen tuottamat luokittelut eri viineille
y_pred = model.predict(X_test)

In [18]:
# Tehtävän vastaukset. Huom! Älä muokkaa tätä solua, vaan aja se, kun olet suorittanut tehtävän. 
# Tallenna ennusteen tulokset y_pred-muuttujaan.
print(f'{len(y_pred)}')

59


## Tehtävä 3
### Aihe: Tarkkuuden mittaaminen

4 pistettä

Hyödynnä `scikit-learn`-kirjaston `metrics`-moduulin funktioita ja laske luokittelutuloksesi **tarkkuus** sekä **sekaannusmatriisi**. Tallenna tarkkuus muuttujaan `acc` ja sekaannusmatriisi muuttujaan `cm`. 

Vinkki: onnistumista voit mitata ainoastaa testiaineiston osalta!

In [19]:
# Kirjoita toteutuksesi tähän soluun.
from sklearn import metrics

# tallennetaan muuttujiin tarkkuus ja sekannuusmatriisi. Eli verrataan testiaineiston tuloksia ennustettuihin lukuihin (y_pred)
acc = metrics.accuracy_score(y_test, y_pred)
cm = metrics.confusion_matrix(y_test, y_pred)

In [20]:
# Tehtävän vastaukset. Huom! Älä muokkaa tätä solua, vaan aja se, kun olet suorittanut tehtävän. 
# Tallenna vastauksesi acc- ja cm-muuttujiin.
print(f'Accuracy: {acc}')
print(f'Confusion matrix:\n {cm}')

Accuracy: 0.9830508474576272
Confusion matrix:
 [[24  1  0]
 [ 0 18  0]
 [ 0  0 16]]
